esp8266:
  board: esp01_1m

sensor:
  - platform: wifi_signal
    name: "Wifi Signal"
    update_interval: 60s
    icon: mdi:wifi
  - platform: uptime
    name: "Uptime"
    update_interval: 60s
    icon: mdi:clock-outline

status_led:
  pin:
    number: GPIO04
  id: led_blue
    
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: True
    name: "Button"
    id: wp_button
    filters:
      delayed_on_off: 100ms # Debouncing
    on_press:
      - switch.toggle: wp_relay

switch:
  # relay itself
  - platform: gpio
    name: "Relay"
    id: wp_relay
    pin: GPIO05
    restore_mode: RESTORE_DEFAULT_OFF
