esphome:
  name: ambience-sensor-8266-papa

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:

ota:

wifi:
  networks:
    # fallback zu zuhause wlan
    - ssid: "zuhause"
    # dein wifi aus den secrets
    - ssid: !secret wifi_ssid
      password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Ambience-Sensor-8266-Papa"
    password: "rjWuLJMqSnhI"

i2c:
  scan: true
  id: bus_a

# Example configuration entry
switch:
  - platform: gpio
    pin: 
      number: D0
    name: "Ambient Sensor LED"
    id: "ambient_sensor_8266_led"

sensor:
  - platform: wifi_signal
    name: "Ambient Sensor WiFi Signal"
    id: "ambient_sensor_8266_wifi_signal"
    update_interval: 30s
  - platform: tcs34725
    i2c_id: bus_a
    red_channel:
      name: "Ambient Sensor Red Channel"
    green_channel:
      name: "Ambient Sensor Green Channel"
    blue_channel:
      name: "Ambient Sensor Blue Channel"
    clear_channel:
      name: "Ambient Sensor Clear Channel"
    illuminance:
      name: "Ambient Sensor Illuminance"
      # id: "ambient_sensor_8266_illuminance"
    color_temperature:
      name: "Ambient Sensor Color Temperature"
      # id: "ambient_sensor_8266_color_temp"
    glass_attenuation_factor: 1.5
    address: 0x29
    update_interval: 2s

captive_portal:
