esphome:
  name: e-ink-pictureframe
  friendly_name: E-Ink Pictureframe

esp32:
  board: firebeetle32

logger:  

# Enable Home Assistant API
api:
  encryption:
    key: !secret enc_default

ota:
  password: "c00cddd74f52489c53801e26986d06ad"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "E-Ink-Infostation"
    password: !secret wifi_ap_password

spi:
  - id: spiBus0
    clk_pin: GPIO18 # SCK # when to read data
    mosi_pin: GPIO19 # aka SDO (serial data out - send data)

font:
  - file: "gfonts://Roboto@700"
    id: robotoFontMed
    size: 27

display:
  - platform: waveshare_epaper
    id: displayComponent
    model: 7.50in-bV3
    #pins
    busy_pin: 
      number: GPIO25
      inverted: false
    reset_pin: GPIO1
    cs_pin: GPIO23 # chip select (SS) # when to listen for data
    dc_pin: GPIO3 # ?
    spi_id: spiBus0
      
    update_interval: 30s # never # is done by state changes
    reset_duration: 2ms
    rotation: 270
    lambda: |-
      it.print(100, 100, id(robotoFontMed), "Hello World");

captive_portal:
