esphome:
  name: led-strip-white-cct-2
  friendly_name: LED Strip White CCT 2

esp8266:
  board: esp01_1m
  # framework:
  #   version: 2.7.4

# Enable logging
logger:

# WLED Config:
# WS2811 colorOrder:BRG numLED: 17 GPIO: 1 maxAmp: 2000mA perLEDAmp: 50mA 

external_components:
  - source: github://pr#4257
    components: [fastled]
    refresh: always

light:
  - platform: neopixelbus
    type: "BRG"
    pin: GPIO1
    num_leds: 19
    name: "LED Strip White CCT 1"
    variant: ws2811
    # method: 
    #   type: esp8266_uart # trying to resolve flicker on color change
    #   bus: 0
    #   async: False
    
# Enable Home Assistant API
api:
  encryption:
    key: !secret enc_default

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Led-Strip-White-Cct-2"
    password: !secret wifi_ap_password

captive_portal:
    