esphome:
  name: led-strip-white-cct-1
  friendly_name: LED Strip White CCT 1

esp8266:
  board: esp01_1m
  # framework:
  #   version: 2.7.4

# Enable logging
logger:

# WLED Config:
# WS2811 colorOrder:BRG numLED: 19 GPIO: 1 maxAmp: 2000mA perLEDAmp: 50mA 

# light:
#   - platform: fastled_clockless
#     chipset: WS2811
#     pin: GPIO1
#     num_leds: 19
#     rgb_order: BRG
#     name: "LED Strip White CCT 1"

# Enable Home Assistant API
api:
  encryption:
    key: !secret enc_default

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-Led-Strip-1 Fallback Hotspot"
    password: !secret wifi_ap_password

captive_portal:
    