esphome:
  name: led-strip-white-cct-2
  friendly_name: LED Strip White CCT 2

esp8266:
  board: esp01_1m

# Enable logging
logger:

# WLED Config:
# WS2811 colorOrder:BRG numLED: 17 GPIO: 1 maxAmp: 2000mA perLEDAmp: 50mA 

light:
  - platform: neopixelbus
    type: "BRG"
    pin: GPIO3
    num_leds: 17
    name: "LED Strip White CCT 2"
    variant: ws2811
    
switch:
  - platform: restart
    name: "Restart Node"

sensor:
  - platform: wifi_signal
    name: "Wifi Signal"
    update_interval: 60s
    icon: mdi:wifi
  - platform: uptime
    name: "Uptime"
    update_interval: 60s
    icon: mdi:clock-outline
    
# Enable Home Assistant API
api:
  encryption:
    key: !secret enc_default

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Led-Strip-White-Cct-2"
    password: !secret wifi_ap_password

captive_portal:
    