esphome:
  name: led-strip-white-cct-1
  friendly_name: LED Strip White CCT 1

esp8266:
  board: esp01_1m
  # framework:
  #   version: 2.7.4

# Enable logging
logger:

# WLED Config:
# WS2811 colorOrder:BRG numLED: 19 GPIO: 1 maxAmp: 2000mA perLEDAmp: 50mA 

# external_components:
#   - source: github://pr#4257
#     components: [fastled]
#     refresh: always

light:
  - platform: neopixelbus
    type: "BRG"
    pin: GPIO3
    num_leds: 19
    name: "LED Strip White CCT 1"
    variant: ws2811
    # method: 
    #   type: esp8266_uart # trying to resolve flicker on color change
    #   bus: 0
    #   async: False

  # - platform: fastled
  #   chipset: WS2811
  #   data_pin: GPIO3
  #   num_leds: 19
  #   rgb_order: BRG
  #   name: "LED Strip White CCT 1"

switch:
  - platform: restart
    name: "Restart Node"

sensor:
  - platform: wifi_signal
    name: "Wifi Signal"
    update_interval: 60s
    icon: mdi:wifi
  - platform: uptime
    name: "Uptime"
    update_interval: 60s
    icon: mdi:clock-outline
    
# Enable Home Assistant API
api:
  encryption:
    key: !secret enc_default

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Led-Strip-White-Cct-2"
    password: !secret wifi_ap_password

captive_portal:
    