esphome:
  name: wall-plug-esp8266-swa11
  friendly_name: Wall Plug 3 ESP8266 SWA11

# include base config for all the same devices
<<: !include component/wall-plug-base-config.yaml

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret enc_default

ota:
  platform: esphome
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # manual ip as this esp device has issues with asus smart-connect feature
  manual_ip:
    static_ip: 192.168.2.106
    gateway: 192.168.2.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Wall-Plug-Esp8266-Swa11"
    password: !secret wifi_ap_password

captive_portal:
