esphome:
  name: wall-plug-2-esp8266-swa11
  friendly_name: Wall Plug 2 ESP8266 SWA11

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:

ota:
  on_error:
    then:
      - logger.log:
          format: "OTA update error %d"
          args: ["x"]
  on_state_change:
    then:
      - logger.log:
          format: "OTA state change %d"
          args: ["state"]


sensor:
  - platform: wifi_signal
    name: "Wifi Signal"
    update_interval: 60s
    icon: mdi:wifi

  - platform: uptime
    name: "Uptime"
    update_interval: 60s
    icon: mdi:clock-outline

status_led:
  pin:
    number: GPIO04
    # inverted: True
  id: led_blue
    
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: True
    name: "Button"
    id: wp_button
    filters:
      delayed_on_off: 100ms # Debouncing
    on_press:
      - switch.toggle: wp_relay

# not needed as red LED is wired in to relay I think
  # output:
  #   - platform: gpio
  #     pin: GPIO05
  #     inverted: true
  #     id: led_red

switch:
  # relay itself
  - platform: gpio
    name: "Relay"
    id: wp_relay
    pin: GPIO05
    restore_mode: RESTORE_DEFAULT_OFF

  # alternate control variant including synthetic (?) switch I think
  # - platform: template
  #   name: "Switch"
  #   id: wp_button_switch
  #   # filters:
  #   #   delayed_on_off: 100ms # Debouncing
  #   icon: mdi:power
  #   optimistic: true
  #   turn_on_action:
  #     - switch.turn_on: wp_relay
  #     # - output.turn_on: led_red
  #   turn_off_action:
  #     - switch.turn_off: wp_relay
  #     # - output.turn_off: led_red

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # manual ip as this esp device has issues with asus smart-connect feature
  manual_ip: 
    static_ip: 192.168.2.222
    gateway: 192.168.2.1
    subnet: 255.255.255.0


  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Wall-Plug-2-Esp8266-Swa11"
    password: "PLYZi91ws49a"

captive_portal:
    